### ISSUE TITLE
Continuous integration not only for Linux?

### ISSUE THREAD

**Issue by masalmon** [osmdatar/osmdata#24]
* Add CI on OSX via Travis? E.g. I do it [here](https://github.com/masalmon/rtimicropem/blob/master/.travis.yml) 

* Add CI on Windows via Appveyor?

**Comment by mpadge** [comment]
Absolutely essential - I just haven't gotten around to doing it

**Comment by mpadge** [comment]
Thanks for the impetus @masalmon - now passing for Linux, OSX, and Windows. I had to [tweak the configure file](https://github.com/osmdatar/osmdata/blob/master/configure#L6-L7) to do an OS check, because the `lgcov` library is Linux only -- let me know if you've got any better ideas for how to do this, otherwise I'll close this issue.

**Comment by masalmon** [comment]
Well I know Windows only :grin:

Awesome that you added both! :clap:

**Comment by mpadge** [comment]
And just for the record, I'm going to remove `r:devel` from the `.travis.yml` because these fail for external reasons (OSX because of apparently [missing deps](https://travis-ci.org/osmdatar/osmdata/jobs/185168440#L1585) and Linux because of [my dinky configure file](https://travis-ci.org/osmdatar/osmdata/jobs/185168439#L2877). Okay, that latter could maybe be fixed but i've got better things to do right now ...

**Comment by Robinlovelace** [comment]
Awesome that we now have appeyor. Thanks loads for the input + implementation.
