### ISSUE TITLE
Strange error when only a bb is given in a query

### ISSUE THREAD

**Issue by Robinlovelace** [osmdatar/osmdata#43]
Reproducible example:

```r
q <- opq (bbox="Kunming, China")
osmdata_sf (q)
```

```
Error in rcpp_osmdata_sf(doc) : unknown member_type
```

But this works:

```r
osmdata_sf (add_feature(q, key = "highway"))
```

```
Object of class 'osmdata' with:
                 $bbox : 24.8915153,102.5417638,25.2115153,102.8617638
        $overpass_call : The call submitted to the overpass API
            $timestamp : [ Sun Feb 26 23:29:43 2017 ]
           $osm_points : 'sf' Simple Features Collection with 50300 points
            $osm_lines : 'sf' Simple Features Collection with 5106 linestrings
         $osm_polygons : 'sf' Simple Features Collection with 65 polygons
       $osm_multilines : 'sf' Simple Features Collection with 0 multilinestrings
    $osm_multipolygons : 'sf' Simple Features Collection with 0 multipolygons
```

Is it because the query is simply too large?

**Comment by Robinlovelace** [comment]
Update: it definitely can work with just a bb, as illustrated for the village where I went to school:

```r
q = opq("Weobley")
d = osmdata_sp(q = q)
```

![image](https://cloud.githubusercontent.com/assets/1825120/23344888/4854bc86-fc7c-11e6-8b02-10f650377127.png)

**Comment by mpadge** [comment]
Damn you @Robinlovelace ! That's a can-o-worms! I didn't know that OSM relations can themselves contain relations, and obviously need to incorporate that reality ...

**Comment by Robinlovelace** [comment]
Haha well at least it's not me making typos for once!

**Comment by mpadge** [comment]
okay, I think [this commit](https://github.com/osmdatar/osmdata/commit/0ec6846657dec273ab9035fd2f541bf888eeb417) was actually all it took to fix it, but this is one to keep in mind. You can check yourself that it all works, although I don't recommend doing an `osmdata_sp()` on it, as that's pretty time-consuming.

The example is, however, not a great one, because the relation is **not** a multipolygon, but it may be that the current code does not properly handle multipolygon relations within multipolygon relations. On the other hand, such things may not exist within OSM? Although we could open an issue to flag that, it could also be years before such a thing might arise, so I'd prefer to simply close this now and just keep the issue ever so vaguely in mind.

**Comment by Robinlovelace** [comment]
Still not working form me after rebuild incorporating your fix:

```
nrow (osmdata_sf (q)$osm_points)
Error in rcpp_osmdata_sf(doc) : unknown member_type
```

**Comment by mpadge** [comment]
Can you check again please Robin, coz it's all good by me here. Generates a royal mess of data (this is a city of 4 mil!), but all works.
```
> q <- opq ('kunming china')
> nrow (osmdata_sf (q)$osm_points)
359131
```

**Comment by Robinlovelace** [comment]
Verified:

```r
d <- osmdata_sf(q)
```

![image](https://cloud.githubusercontent.com/assets/1825120/23376872/af90ea10-fd25-11e6-9672-4935bec506e4.png)
