### ISSUE TITLE
building

### ISSUE THREAD

**Issue by masalmon** [osmdatar/osmdata#46]
When building the package every time it creates new files under src/ but I guess it's normal?

![src](https://cloud.githubusercontent.com/assets/8360597/23355886/0895f9c8-fcd8-11e6-96c4-1d7cd1568eac.png)

**Comment by Robinlovelace** [comment]
Those also appear on my computer so +1 for reporting.

**Comment by masalmon** [comment]
I also wonder if the `pkgdown` issues might be due to the knit thing in the makefile? Why do we need the knit part of the makefile?

In general, why are configure/makefile/cleanup necessary? Sorry if it is a very stupid question :-)

**Comment by masalmon** [comment]
If I erase the three files (configure/makefile/cleanup), the package still seems to work :thinking:

**Comment by masalmon** [comment]
not sure if relevant http://stackoverflow.com/questions/28521074/r-cmd-build-leaves-compiled-o-files-in-src-folder

**Comment by mpadge** [comment]
The files that get created in `src` are the compiled objects, which are an intrinsic and utterly necessary part of the package. The `makefile` is my personal equivalent of a `.Rproj` file, and will not affect any build on any os (both of these can technically be deleted). `configure` and `cleanup` on the other hand are absolutely necessary. Well, strictly speaking, `configure` is necessary for travis only, not for personal package installation, but it's still entirely standard practice to include it.

What `configure` does is to ensure that symbolic tokens from the compiled objects can be used to evaluate code coverage. It simple passes the appropriate names to `src/Makevars`. The `cleanup` script **should** then remove all of these objects upon successful installation, but ... I recall from somewhere that this might not always work. (@masalmon - the stackoverflow issue is not the solution here, because these files can't be `.Rignore`d; the issue was discussed somewhere else on github.)

**Comment by masalmon** [comment]
Thanks for the explanation. 

So what could be the reason for the `pkgdown` problems (for the README and Robin's vignette)? :thinking: @Robinlovelace could you try `pkgdown`? @mpadge what was your `pkgdown` issue?

**Comment by mpadge** [comment]
First things first - I just confirmed that `cleanup` works as it should on my (linux) system. @masalmon - can you do a `R CMD build --no-build-vignettes osmdata` and confirm that `src` does **NOT** contain these files?

As for `pkgdown` - i can't use it because it forces upgrade to `devtools 1.12.0.9000`, which farms off stuff  to the new `pkgbuild` and `pkgload` packages, and the former has a massive bug that's [still not fixed](https://github.com/r-pkgs/pkgbuild/pull/1) - @Robinlovelace install `pkgdown` at your own peril!

**Comment by masalmon** [comment]
yes the .tar.gz does not contain these files with this command :+1:
